default: &default
  adapter: <%= ENV["DATABASE_ADAPTER"] %>
  encoding: utf8

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
test:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
