development:
  adapter: mysql2
  database: wifi_uff_location_development
  username: root
  password: root
test:
  adapter: mysql2
  database: wifi_uff_location_test
  username: root
  password: root

production:
  database: wifi_uff_location_production
  username: root
  password: 
