development:
  adapter: mysql2
  encoding: utf8
  database: wifi_uff_location_development
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  adapter: mysql2
  encoding: utf8
  database: wifi_uff_location_test
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: wifi_uff_location_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
