# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dbb6c229a0d6ced9a08449fc4ba64ea864e44fd961a76a5b6d5028b1d7f5bdd79cd48baed738c1978ef0e9c19db5914f8d9df641d0814d92adbcced1d84c7c6

test:
  secret_key_base: 707444a63610f8f69971abe5fec99316ca046d3d3624cc51aa2da7e50d2abaef9f2f358e67fce64e3983216fee524ee097e2faf2a5b4d9c27bee8c883ed3c1fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
